#!/bin/sh
# chkconfig: 345 20 80
# description: VBox Machine server
# Source function library.
. /etc/rc.d/init.d/functions

run_by_init() {
([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

export PATH="${PATH:+$PATH:}/bin:/usr/bin:/usr/sbin:/sbin"

VM_USER="vbox"
SU="su $VM_USER -c"
VBOXMANAGE="VBoxManage -nologo"
VBOXHeadless="/usr/bin/VBoxHeadless"

start () {
    echo "Starting VBox Machine"
    $SU "$VBOXHeadless -startvm "srv-win-pdc" &"
        }
                
    stop () {
$SU "$VBOXMANAGE list runningvms" | while read VM; do
    echo "Shutting down VM: $VM ..."
$SU "$VBOXMANAGE controlvm "$VM" acpipowerbutton"
    done
        }
    restart() {
    stop
    start
    }
case $1 in
    start)
    start
    ;;
    stop)
    stop
    ;;
restart)
restart
    ;;
    status)
    echo "The following virtual machines are currently running:"
    $SU "$VBOXMANAGE list runningvms" | while read VM; do
        echo -n "$VM ("
echo -n `$SU "VBoxManage showvminfo $VM|grep Name:|sed -e 's/^Name:\s*//g'"`
        echo ")"
        done
            ;;
                *)
echo $"Usage: $prog {start|stop|restart|status}"
exit 3
esac
exit 0